### ISSUE TITLE
Collisions constrained to be within a band, or not

### ISSUE THREAD

**Issue by cjauvin** [go2starr/lshhdc#2]
In the second paragraph of Section 3.4.1 of the MMD book, it says:

> We can use the same hash function for all the bands, but we use a separate bucket
> array for each band, so columns with the same vector in diﬀerent bands will not 
> hash to the same bucket.

As I understand it, it's not the way your code works, as the (single) band-hashing function does not distinguish between bands, and the first band of a document could collide with the second band of another, for instance (at least in theory, because I don't know if it's really likely to happen). In other words, you seem to only have one set of buckets (for all the bands), whereas the book suggests to have as many sets as there are bands. Does that make sense?

**Comment by cjauvin** [comment]
I implemented the change to tackle the issue I raised above:

https://github.com/cjauvin/lshhdc/commit/3c3f985efa29206e80c622a464c5508153001fd4

but as I was testing it, trying to find an example where it would actually make a difference, I began to realize how unlikely it would be to find such a case, simply because the hash functions composing a band are necessarily different from those of the other bands, making this extra mechanism useless for all practical purposes. @escherba and @cjdd3b, as you've been also involved with this code, I'd appreciate your opinion on this if you have the time and interest.

**Comment by escherba** [comment]
@cjauvin Good on you for spotting this. I agree that this would only cause problems under problematic conditions where the chance of collision is unusually high. For practitioners there is no difference between using one bucket array or many.

**Comment by cjauvin** [comment]
Thanks @escherba for your answer. If you happen by chance to have any idea about that broader question I raised recently, regarding minhashing vs simhashing:

http://stats.stackexchange.com/questions/81930/clarification-needed-about-min-sim-hashing-lsh

please feel free to chime in. I ask because it seems that finding clear information about that topic (apart from the MMD book) is not such an easy task.

**Comment by go2starr** [comment]
Looks like I missed the fine print here as well (and some bad whitespace, too).  Good catch.
