### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [go2starr/lshhdc#5]
@go2starr what is the license for your code?

**Comment by ninowalker** [comment]
:+1: Yes, this is a good question. https://help.github.com/articles/open-source-licensing#what-happens-if-i-dont-choose-a-license

**Comment by go2starr** [comment]
Updated w/ MIT license: https://github.com/go2starr/lshhdc/commit/e4d537926a496ea71ee9b691aabaeb16631058ac.  Go forth and use this code!

**Comment by ninowalker** [comment]
Thank you!

**Comment by pombredanne** [comment]
@go2starr thanks !
